version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dlh-cloudres-backend-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o34telgxyxcf"
s3_prefix = "dlh-cloudres-backend-bucket"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
