on:
  push:
    branches:
      - main
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # python test with moto
      - name: Install Python
        uses: actions/setup-python@v3
        with: 
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 moto

      - name: Test Lambda 
        run: python Lambda/test_lambda.py

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Set up AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: SAM Build
        run: sam build --use-container
      
      - name: SAM Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset